# Generated by Django 4.2.16 on 2024-09-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта клиента')),
                ('first_name', models.CharField(help_text='Введите имя', max_length=50, verbose_name='Имя')),
                ('second_name', models.CharField(help_text='Введите фамилию', max_length=50, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, help_text='Введите отчество', max_length=50, null=True, verbose_name='Отчество')),
                ('comment', models.TextField(blank=True, help_text='Введите комментарий', null=True, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('email',),
                'permissions': [('can_view_clients', 'can view clients'), ('can_change_clients', 'can change clients'), ('can_delete_clients', 'can delete clients')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateField(blank=True, null=True, verbose_name='Дата начала рассылки')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='Дата создания рассылки')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата изменения рассылки')),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('completed', 'completed'), ('created', 'created'), ('started', 'started')], default='created', verbose_name='Статус рассылки')),
                ('interval', models.CharField(choices=[('once a minute', 'once a minute'), ('once a day', 'once a days'), ('once a week', 'once a week'), ('once a month', 'once a months')], default='once a day', verbose_name='Интервал рассылки')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания рассылки')),
                ('client', models.ManyToManyField(related_name='mailings', to='mailing.client', verbose_name='Клиент с почтой')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('interval',),
                'permissions': [('can_change_mailing', 'can change mailing'), ('can_delete_mailing', 'can delete mailing'), ('can_view_mailing', 'can view mailing'), ('can_create_mailing', 'can create mailing'), ('can_switch_mailing', 'can switch mailing')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок сообщения', max_length=50, verbose_name='Заголовок сообщения')),
                ('body', models.TextField(help_text='Введите содержание сообщения', verbose_name='Содержание сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ('title',),
                'permissions': [('can_change_message', 'can change message'), ('can_delete_message', 'can delete message')],
            },
        ),
        migrations.CreateModel(
            name='TryMailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_try', models.DateTimeField(auto_now_add=True, verbose_name='Дата последней попытки рассылки')),
                ('status', models.CharField(choices=[('success', 'success'), ('fail', 'fail')], default='success', verbose_name='Статус')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Ответ')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailing.mailing', verbose_name='Рассылка')),
            ],
            options={
                'verbose_name': 'Попытка рассылки',
                'verbose_name_plural': 'Попытки рассылок',
                'ordering': ('status',),
            },
        ),
        migrations.AddField(
            model_name='mailing',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailings', to='mailing.message', verbose_name='Сообщение'),
        ),
    ]
