# Generated by Django 4.2.16 on 2024-09-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='users',
            field=models.ForeignKey(blank=True, help_text='Автор рассылки', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор рассылки'),
        ),
        migrations.AddField(
            model_name='message',
            name='users',
            field=models.ForeignKey(blank=True, help_text='Автор сообщения', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор сообщения'),
        ),
    ]
