# Generated by Django 4.2.16 on 2024-09-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="next_send_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата повтора рассылки"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="interval",
            field=models.CharField(
                choices=[
                    ("once a day", "once a days"),
                    ("once a week", "once a week"),
                    ("once a month", "once a months"),
                ],
                default="once a day",
                verbose_name="Интервал рассылки",
            ),
        ),
    ]
