# Generated by Django 4.2.16 on 2024-09-17 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing', '0003_alter_mailing_users_alter_message_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создал клиента'),
        ),
    ]
