# Generated by Django 4.2.16 on 2024-09-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_alter_client_options_alter_mailing_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('email',), 'permissions': [('can_edit_is_active_client', 'can edit active clients')], 'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('interval',), 'permissions': [('can_edit_is_active_mailing', 'can edit active mailing')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('title',), 'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
    ]
