# Generated by Django 4.2.16 on 2024-09-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите заголовок', max_length=35, verbose_name='Заголовок')),
                ('body', models.TextField(help_text='Введите текст статьи', verbose_name='Текст')),
                ('image', models.ImageField(blank=True, help_text='Загрузите превью статьи', null=True, upload_to='product/photo', verbose_name='Изображение')),
                ('created_at', models.DateField(blank=True, help_text='Укажите дату написания статьи', null=True, verbose_name='Дата написания статьи')),
                ('count_views', models.IntegerField(default=0, verbose_name='Количество просмотров статьи')),
                ('is_publication', models.BooleanField(default=True, verbose_name='Опубликовать?')),
            ],
        ),
    ]
